"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LOAD_FILMS = "LOAD_FILMS";
exports.SELECT_FILM = "SELECT_FILM";
exports.DESELECT_FILM = "DESELECT_FILM";
exports.RATING_PLUS = "RATING_PLUS";
exports.RATING_MINUS = "RATING_MINUS";
exports.RATING_RESET = "RATING_RESET";
exports.SET_VIEW = "SET_VIEW";
exports.ADD_TO_QUEUE = "ADD_TO_QUEUE";
exports.REMOVE_FROM_QUEUE = "REMOVE_FROM_QUEUE";
